networks:
  default:
    name: cloudflare-net
    external: true

secrets:
  cloudflare-tunnel-token:
    external: true

services:
  tunnel:
    image: cloudflare/cloudflared:latest
    secrets:
      - cloudflare-tunnel-token
    environment:
      TUNNEL_TOKEN_FILE: /run/secrets/cloudflare-tunnel-token
    command: tunnel --no-autoupdate --protocol http2 run
    networks:
      - default
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints:
          - node.role==manager