networks:
  default:
    name: metrics-net

volumes:
  victoriametrics-data:
  vmagent-data:

configs:
  vmagent-config.yaml:
    file: ./config/vmagent-config.yaml

services:
  vmagent:
    image: victoriametrics/vmagent:v1.134.0
    volumes:
      - vmagent-data:/vmagentdata
    configs:
      - source: vmagent-config.yaml
        target: /etc/prometheus/prometheus.yml
    command:
      - "--promscrape.config=/etc/prometheus/prometheus.yml"
      - "--remoteWrite.url=http://victoriametrics:8428/api/v1/write"
    deploy:
      placement:
        constraints:
          - node.labels.ssd_storage==true

  victoriametrics:
    image: victoriametrics/victoria-metrics:v1.134.0
    command: -storageDataPath=/victoriametrics-data -memory.allowedPercent=20
    networks:
      default:
        aliases:
          - victoriametrics
    deploy:
      mode: replicated
      placement:
        constraints:
          - node.labels.ssd_storage==true
      replicas: 1
    volumes:
      - type: volume
        source: victoriametrics-data
        target: /victoriametrics-data
  
  node-exporter:
    image: prom/node-exporter:v1.10.2
    command:
      - '--path.sysfs=/host/sys'
      - '--path.procfs=/host/proc'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
      - '--no-collector.ipvs'
    deploy:
      mode: global
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    volumes:
      - /:/rootfs:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.54.1
    command:
      - --port=8080
      - --housekeeping_interval=10s
      - --docker_only=true
      - --storage_driver=none
    deploy:
      mode: global
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
      labels:
        - prometheus.port=8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro    