global:
  scrape_interval: 10s

scrape_configs:
- job_name: vmagent
  static_configs:
  - targets:
    - vmagent:8429

- job_name: vmalert
  static_configs:
  - targets:
    - vmalert:8880

- job_name: victoriametrics
  static_configs:
  - targets:
    - victoriametrics:8428

- job_name: 'cadvisor'
  dns_sd_configs:
   - names: ['tasks.cadvisor']
     type: 'A'
     port: 8080

- job_name: 'node-exporter'
  dns_sd_configs:
    - names: ['tasks.node-exporter']
      type: 'A'
      port: 9100